name = "blog-uoc-1"
license = "MIT"
licenselink = ""
description = "Blog UOC estil blau"
homepage = "http://www.uoc.edu/"
tags = ["blog", "uoc", "education"]
features = ["blog"]
min_version = 0.13

[author]
    name = "ais"
    homepage = "https://www.uoc.edu"

